# Generated by Django 5.2.13 on 2026-05-06 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_create_default_users'),
    ]

    operations = [
    ]
