# Generated by Django 5.2.13 on 2026-05-06 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_ensure_admin_role'),
    ]

    operations = [
    ]
